### ISSUE TITLE
Cannot Load

### ISSUE THREAD

**Issue by EmosewaGamer** [SuperScary/HeavyInventories-Localization#3]
Whenever I try to load the game with the mod, I get this:
 
![image](https://user-images.githubusercontent.com/25333164/28411985-f86d1c6c-6d42-11e7-8bc8-5e54c7c6a261.png)

**Comment by WazWaz** [comment]
This is particularly a problem when using the Curse Launcher / Twitch app to install HeavyIndustries, because it automatically installs the SuperCore dependency, causing the above. To work around, need to delete the SuperCore from the mods directory (and hope Curse doesn't helpfully re-download it...)

**Comment by XvSkItZvX** [comment]
That's true, I made it here after giving it a test run for a pack I'm working on...I use MultiMC for testing and manually download the mods. If Curse/Twitch is kind enough to redownload, after deleting, just add ".disabled" after ".jar" (SuperCore-1.12-1.1.jar.disabled) ...that way you still have it but it won't be loaded.

**Comment by SuperScary** [comment]
Issue has been solved. Will be fixed in update 2.0.1
